### ISSUE TITLE
How to load local files on web

### ISSUE THREAD

**Issue by manuel15557** [GilbertoGojira/TinyAssetLoader#1]
hello! Thanks for making this package.

I have a tiny project that builds web. I have a lot of text in the game, which I'd like to load dynamically.

In the description it says "External asset loading only loads local files **in the desktop versions** but in WebGL any remote file can be loaded because it uses XMLHttpRequestin the underlying plugin."

When I try to asset load (while building to web) it always tries to do an XML request and skips trying to look for the file locally. How do I force the asset to be loaded locally?

I think I could just be using the wrong filepath, but if so, then what is the root? (the asset folder? the resource folder?).
for example
EntityManager.AddBufferFromString<AssetFilename>(EntityManager.CreateEntity() , "Discoveries/particles.txt");
(what should be the full filepath for particles.txt for this to work?)

the above ends in this error in the web console.
Tiny3D.html:6854 GET http://localhost:8084/Discoveries/particles.txt 404 (Not Found)

**Comment by GilbertoGojira** [comment]
In web builds all files are treated as remote because of using XMLHttpRequest. When you refer to local it means that the file in your web server and using local paths like in your example should work.
Are you sure you have manually copied "Discoveries/particles.txt" to you wasm built directory?

**Comment by manuel15557** [comment]
oh I see, so my files have to be in the wasm build folder, not within my unity asset folder.

In normal unity you can do Resource.load() which will load assets from the resource folder, is there an equivalent way of doing this with your package?

**Comment by GilbertoGojira** [comment]
Your files can be located anywhere as long as they are accessible from an url. In you example they will be access as relative path on your web root folder.
In Tiny there is no Resource similar pipeline yet. My package leverages the internal asset loading pipeline in order for any file to be loaded and binary data.
